cat > ~/ai-chat-app/docker-compose.yml << 'EOL'
version: '3'
services:
  backend:
    build: ./backend
    container_name: ai-chat-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: ai-chat-frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
      - VITE_API_URL=${VITE_API_URL}
      - VITE_IMAGE_KIT_ENDPOINT=${VITE_IMAGE_KIT_ENDPOINT}
      - VITE_IMAGE_KIT_PUBLIC_KEY=${VITE_IMAGE_KIT_PUBLIC_KEY}
      - VITE_GEMINI_PUBLIC_KEY=${VITE_GEMINI_PUBLIC_KEY}
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
EOL